import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const neuePower = localFont({
  src: "./fonts/NeuePower-Ultra.woff",
  variable: "--font-neue-power",
});

const poppins = localFont({
  src: [
    {
      path: "./fonts/Poppins-Medium.ttf",
      weight: "500",
    },
    {
      path: "./fonts/Poppins-Semibold.ttf",
      weight: "600",
    },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Honest UX | Portfolio Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${neuePower.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
